name: ec2instance_create
on:
  workflow_dispatch:
       inputs :
          condition:
            type: boolean
            description: "condition"
            default: false
          ec2-region:
              description: "ec2-region"
              required: true
 
    
env:
  bucket: paraskambojbuc
  tfstate_file: ec2.tfstate
  # condition: {{github.event.inputs.condition}}
  aws-region: ${{github.event.inputs.ec2-region}}

jobs:
  terraform_plan:
    name: terraform
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ inputs.condition == 'true'}}
      - name: Setup terraform hashicorp
        uses: hashicorp/setup-terraform@v2 
        with:
          terraform_version: 1.3.4

        
      
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1   
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          Aws-region: ${{env.aws-region}}

      
      - name: terraform init  
        run: |
          cd s3-backend
          terraform init -reconfigure -backend-config="bucket=${{env.bucket}}" -backend-config="key=${{env.tfstate_file}}"
      
      - name: terraform plan
        run: |
          cd s3-backend
          terraform plan 
      - name: terraform apply  
      
        run: |
          cd s3-backend
          terraform apply -auto-approve